In [1]:
import pandas as pd
tcs = pd.read_csv("Прошлые данные - TCSGDR (2).csv")
tcs

           Дата      Цена     Откр.     Макс.      Мин.    Объём  Изм. %
0    24.10.2022  2.485,00  2.473,50  2.534,00  2.455,00  181,57K   1,06%
1    21.10.2022  2.459,00  2.513,00  2.513,00  2.374,50  749,89K  -1,76%
2    20.10.2022  2.503,00  2.619,00  2.647,00  2.466,50  671,12K  -4,06%
3    19.10.2022  2.609,00  2.601,00  2.635,00  2.530,50  300,45K  -0,61%
4    18.10.2022  2.625,00  2.710,00  2.759,00  2.600,50  399,11K  -2,85%
..          ...       ...       ...       ...       ...      ...     ...
195  14.12.2021  5.970,00  5.890,00  6.047,80  5.400,60  663,53K   0,85%
196  13.12.2021  5.919,80  6.330,00  6.444,80  5.870,00  730,86K  -6,19%
197  10.12.2021  6.310,20  6.360,00  6.392,00  6.113,20  432,56K  -0,19%
198  09.12.2021  6.322,40  6.212,00  6.523,00  6.020,00  671,40K   1,23%
199  08.12.2021  6.245,40  6.599,80  6.750,00  6.141,00  829,89K  -4,84%

[200 rows x 7 columns]

In [2]:
tcs_p = list(tcs['Цена'])[::-1]
tcs_p

['6.245,40',
 '6.322,40',
 '6.310,20',
 '5.919,80',
 '5.970,00',
 '6.140,20',
 '6.112,60',
 '6.119,00',
 '6.006,20',
 '6.105,00',
 '5.960,00',
 '5.972,80',
 '5.991,80',
 '6.013,20',
 '6.099,00',
 '5.960,80',
 '6.118,00',
 '6.364,40',
 '6.264,60',
 '5.805,00',
 '5.801,60',
 '5.830,00',
 '5.945,00',
 '6.192,80',
 '5.832,80',
 '5.509,80',
 '5.295,00',
 '4.720,00',
 '4.650,00',
 '4.822,80',
 '4.828,00',
 '4.600,00',
 '4.952,00',
 '5.089,80',
 '5.400,00',
 '5.421,20',
 '5.587,00',
 '5.665,00',
 '5.554,00',
 '5.235,00',
 '5.184,50',
 '5.005,00',
 '5.067,50',
 '5.698,00',
 '5.846,50',
 '5.314,50',
 '5.223,00',
 '5.519,50',
 '5.488,50',
 '5.147,00',
 '4.821,50',
 '4.475,00',
 '4.488,50',
 '3.039,50',
 '3.054,50',
 '2.990,00',
 '2.980,00',
 '3.318,50',
 '3.499,50',
 '3.664,00',
 '3.601,00',
 '3.500,00',
 '3.470,00',
 '3.274,50',
 '3.269,00',
 '3.217,00',
 '3.172,00',
 '3.010,00',
 '2.993,00',
 '2.722,00',
 '2.540,00',
 '2.590,00',
 '2.485,00',
 '2.270,00',
 '1.908,00',
 '2.073,00',
 '2.520,00',
 '2.700,00',
 '2.608,00',
 '2.402,00',
 '2.453,00',
 '2.304,00',
 '2.245,50',
 '2.032,00',
 '2.130,00',
 '2.185,00',
 '2.380,00',
 '2.402,00',
 '2.236,50',
 '2.194,00',
 '2.129,00',
 '2.146,50',
 '2.155,50',
 '2.220,50',
 '2.201,00',
 '2.164,00',
 '2.111,50',
 '2.110,50',
 '2.105,00',
 '2.018,00',
 '1.900,00',
 '1.859,50',
 '1.886,00',
 '1.777,00',
 '1.701,00',
 '1.597,00',
 '1.651,50',
 '1.737,00',
 '1.676,00',
 '1.725,00',
 '1.673,00',
 '1.649,00',
 '1.654,50',
 '1.635,00',
 '1.672,00',
 '1.927,00',
 '1.810,00',
 '1.804,00',
 '1.861,00',
 '2.012,00',
 '2.039,00',
 '2.100,00',
 '2.031,00',
 '2.013,00',
 '1.980,00',
 '1.943,50',
 '1.895,00',
 '1.879,50',
 '1.901,50',
 '1.876,00',
 '1.813,50',
 '1.771,00',
 '1.759,00',
 '1.854,00',
 '1.969,50',
 '1.994,50',
 '1.963,00',
 '1.947,50',
 '1.950,00',
 '1.884,50',
 '1.810,00',
 '1.836,00',
 '1.869,50',
 '1.859,00',
 '1.891,50',
 '1.917,50',
 '2.045,00',
 '2.149,50',
 '2.230,00',
 '2.252,00',
 '2.415,50',
 '2.430,50',
 '2.480,00',
 '2.700,00',
 '2.720,00',
 '2.717,00',
 '2.579,50',
 '2.626,00',
 '2.630,00',
 '2.715,00',
 '2.688,50',
 '2.712,50',
 '2.738,50',
 '2.766,50',
 '2.754,00',
 '2.670,00',
 '2.714,00',
 '2.768,50',
 '2.787,00',
 '2.950,00',
 '3.010,00',
 '2.994,00',
 '3.030,50',
 '3.106,00',
 '3.188,00',
 '2.781,00',
 '2.662,50',
 '2.790,00',
 '2.552,00',
 '2.105,00',
 '2.413,00',
 '2.395,00',
 '2.291,00',
 '2.374,00',
 '2.636,00',
 '2.640,00',
 '2.557,00',
 '2.523,00',
 '2.372,50',
 '2.483,50',
 '2.496,00',
 '2.504,00',
 '2.604,50',
 '2.568,50',
 '2.702,00',
 '2.625,00',
 '2.609,00',
 '2.503,00',
 '2.459,00',
 '2.485,00']

In [3]:
gazp = pd.read_csv("Прошлые данные - GAZP (1).csv")
gazp

           Дата    Цена   Откр.   Макс.    Мин.    Объём  Изм. %
0    24.10.2022  165,82  168,00  168,79  164,82   24,15M  -0,70%
1    21.10.2022  166,99  160,00  169,96  159,03   35,54M   3,88%
2    20.10.2022  160,75  161,69  162,48  160,15   14,36M  -0,33%
3    19.10.2022  161,29  159,10  161,50  157,40   23,66M   0,68%
4    18.10.2022  160,20  164,00  164,64  159,10   20,79M  -1,86%
..          ...     ...     ...     ...     ...      ...     ...
198  14.12.2021  319,35  307,00  320,00  289,78  168,69M   3,93%
199  13.12.2021  307,26  333,08  334,88  305,76  140,58M  -7,45%
200  10.12.2021  332,00  337,36  338,31  329,98   44,65M  -1,37%
201  09.12.2021  336,60  341,28  344,20  335,72   61,41M  -1,15%
202  08.12.2021  340,50  346,00  348,47  336,53   78,33M  -1,29%

[203 rows x 7 columns]

In [4]:
gazp_p = list(gazp['Цена'][:200])[::-1]

In [5]:
agr = pd.read_csv("Прошлые данные - AGRODR.csv")
agr

           Дата      Цена     Откр.     Макс.      Мин.    Объём  Изм. %
0    24.10.2022    816,40    807,40    822,40    805,00   73,20K   2,08%
1    21.10.2022    799,80    798,60    801,60    792,20   21,69K   0,15%
2    20.10.2022    798,60    801,00    805,60    795,20   15,78K   0,78%
3    19.10.2022    792,40    797,80    808,20    772,00   33,96K  -0,95%
4    18.10.2022    800,00    805,80    814,00    793,00   30,14K   0,00%
..          ...       ...       ...       ...       ...      ...     ...
195  14.12.2021  1.064,00  1.048,60  1.085,00  1.008,20  256,66K   1,47%
196  13.12.2021  1.048,60  1.108,60  1.114,60  1.037,20  203,04K  -4,03%
197  10.12.2021  1.092,60  1.120,80  1.128,80  1.092,40   91,12K  -3,10%
198  09.12.2021  1.127,60  1.117,00  1.137,00  1.117,00   40,05K   1,13%
199  08.12.2021  1.115,00  1.148,40  1.160,80  1.109,40   75,69K  -2,28%

[200 rows x 7 columns]

In [6]:
agr_p = list(agr['Цена'])[::-1]

In [7]:
afk = pd.read_csv("Прошлые данные - AFKS.csv")
afk_p = list(afk['Цена'][:200])[::-1]

In [8]:
p = [tcs_p, gazp_p, agr_p, afk_p]
n = len(p)
r = [[] for i in range(n)]
mu = [0 for i in range(n)]
d = [0 for i in range(n)]

In [9]:
afk_p

['23,25',
 '22,50',
 '22,64',
 '22,52',
 '22,34',
 '22,33',
 '22,56',
 '23,60',
 '23,53',
 '23,36',
 '24,52',
 '24,71',
 '23,59',
 '24,20',
 '23,86',
 '24,13',
 '24,16',
 '22,98',
 '22,54',
 '22,16',
 '21,47',
 '22,07',
 '21,87',
 '21,45',
 '19,94',
 '19,81',
 '19,48',
 '20,27',
 '19,99',
 '20,50',
 '20,59',
 '20,23',
 '19,67',
 '19,75',
 '19,42',
 '20,01',
 '20,52',
 '20,27',
 '19,35',
 '19,21',
 '20,25',
 '21,32',
 '20,19',
 '18,89',
 '15,95',
 '17,77',
 '12,65',
 '12,63',
 '12,65',
 '12,89',
 '12,60',
 '11,65',
 '11,54',
 '12,50',
 '13,91',
 '13,89',
 '14,10',
 '13,45',
 '13,49',
 '13,62',
 '13,21',
 '13,20',
 '13,04',
 '13,20',
 '12,53',
 '12,67',
 '12,10',
 '12,14',
 '12,40',
 '12,55',
 '12,30',
 '12,18',
 '12,60',
 '12,59',
 '12,50',
 '12,91',
 '12,60',
 '12,84',
 '12,90',
 '12,65',
 '12,11',
 '12,22',
 '12,29',
 '12,35',
 '13,37',
 '13,35',
 '12,76',
 '12,41',
 '12,60',
 '12,86',
 '13,00',
 '12,76',
 '12,75',
 '12,96',
 '13,19',
 '12,83',
 '12,84',
 '12,54',
 '12,47',
 '12,56',
 '12,30',
 '12,45',
 '12,55',
 '12,46',
 '12,69',
 '12,51',
 '12,83',
 '12,97',
 '12,90',
 '13,53',
 '13,97',
 '14,57',
 '14,60',
 '14,88',
 '14,50',
 '14,85',
 '15,00',
 '15,00',
 '15,16',
 '15,05',
 '15,04',
 '14,80',
 '14,17',
 '13,38',
 '13,11',
 '13,70',
 '13,47',
 '13,37',
 '13,20',
 '13,01',
 '13,56',
 '13,99',
 '14,35',
 '14,00',
 '13,91',
 '14,77',
 '14,17',
 '13,76',
 '13,78',
 '14,23',
 '13,73',
 '13,77',
 '14,10',
 '14,30',
 '14,29',
 '14,30',
 '14,58',
 '14,80',
 '14,51',
 '14,45',
 '14,29',
 '14,44',
 '14,68',
 '14,46',
 '14,36',
 '14,50',
 '14,58',
 '14,54',
 '14,66',
 '14,46',
 '14,65',
 '15,43',
 '14,81',
 '14,74',
 '14,71',
 '15,01',
 '15,07',
 '15,00',
 '14,79',
 '14,79',
 '14,83',
 '14,89',
 '13,58',
 '12,62',
 '12,78',
 '11,76',
 '10,34',
 '10,73',
 '10,69',
 '10,53',
 '10,68',
 '11,23',
 '11,00',
 '10,75',
 '10,61',
 '10,14',
 '10,58',
 '10,70',
 '10,79',
 '10,99',
 '10,99',
 '11,50',
 '11,32',
 '11,41',
 '11,65',
 '11,85',
 '11,84',
 '12,32',
 '12,65',
 '12,86']

In [10]:
for j in range(n):
  for i in range(len(p[j])):
    p[j][i] = float(p[j][i].replace('.', '').replace(',', '.'))
  # вычисление нетто-доходности
  for i in range(1, len(p[j])):
    r[j].append((p[j][i]/p[j][i-1]) - 1)
  # вычисляем выборочное средние
  mu[j] = sum(r[j])/len(r[j])
  d[j] = sum([(r[j][i] - mu[j]) ** 2 for i in range(len(r[j]))])/len(r[j])

In [11]:
print('mu:', mu)
print('d:', d)

mu: [-0.0030704113199396146, -0.0017380221809239747, -0.0008590625627233621, -0.0021564388748883394]
d: [0.0029646683279163674, 0.002544738446124584, 0.0014521046898677064, 0.0015149793888364438]

In [12]:
cov = [[0 for i in range(n)] for i in range(n)]
for j in range(n):
  for i in range(n):
    cov[j][i] = sum([(r[j][k] - mu[j])*(r[i][k] - mu[i]) for k in range(len(r[j]))])/len(r[j])

In [13]:
#Выводим матрицу ковариации
for i in range(n):
  print(cov[i])

[0.0029646683279163674, 0.0007160768552567892, 0.0010226229532336922, -0.0001730805479968109]
[0.0007160768552567892, 0.002544738446124584, 0.00039774059672175843, 8.80733785128697e-05]
[0.0010226229532336922, 0.00039774059672175843, 0.0014521046898677064, 8.363114289645438e-05]
[-0.0001730805479968109, 8.80733785128697e-05, 8.363114289645438e-05, 0.0015149793888364438]

In [14]:
m = (max(mu) + min(mu))/2

In [16]:
from sympy import *
k = 10

X = list(symbols(' x1:'+str(n+1)))
LL = list(symbols('l0:'+str(n+3)))
XLL = X.copy()
XLL.extend(LL)

D = sum([sum([X[i]*X[j]*cov[i][j] for i in range(n)]) for j in range(n)])

q1 = sum([X[i]*mu[i] for i in range(n)]) - m

q2 = sum([X[i] for i in range(n)]) - 1

Q = []
for i in range(0,n):
  Q.append(X[i]*LL[i+3])
L = 1*D+LL[1]*q1+LL[2]*q2

for qi in Q:
  L = L - qi
Lx = []
for xi in X:
  Lx.append(L.diff(xi))

LxQqq = Lx.copy()
LxQqq.extend(Q)
LxQqq.append(q2)
LxQqq.append(q1)

#solutions=solve([Lx[0], Lx[1], Lx[2], Q[0], Q[1], Q[2], q2, q1])
solutions=solve(LxQqq)
  #A = np.array[LX,Q,q2,q1]
  #solutions=solve([Lx], X,LL)

In [ ]:
solutions

In [31]:
#Ищем точки потенциального минимум дисперсии
for i in range(len(solutions)):
  solution_list = list(solutions[i].values())[2:]
  if all(x >= 0 for x in solution_list):
    print(solutions[i])

{l1: 0.155833736867698, l2: -0.00104358135179688, l3: 0.0, l4: 0.0, l5: 0.0, l6: 0.0, x1: 0.169927687374602, x2: 0.161064634380997, x3: 0.215526538456399, x4: 0.453481139788002}

In [32]:
#Ищем точки потенциального максимума дисперсии
for i in range(len(solutions)):
  solution_list = list(solutions[i].values())[2:]
  if all(x <= 0 for x in solution_list[:n]) and all(x >= 0 for x in solution_list[n:]):
    print(solutions[i])

{l1: -1.70354167236228, l2: -0.00742795255175996, l3: 0.0, l4: 0.0, l5: -0.00495636681173390, l6: -0.00366709641809977, x1: 0.170156565952658, x2: 0.829843434047342, x3: 0.0, x4: 0.0}
{l1: 0.126776460971048, l2: -0.00123682472267358, l3: 0.0, l4: -0.000845334346868592, l5: 0.0, l6: 0.0, x1: 0.203372581368779, x2: 0.0, x3: 0.291032652181526, x4: 0.505594766449695}
{l1: 0.155833736867698, l2: -0.00104358135179688, l3: 0.0, l4: 0.0, l5: 0.0, l6: 0.0, x1: 0.169927687374602, x2: 0.161064634380997, x3: 0.215526538456399, x4: 0.453481139788002}
{l1: 0.626026392122629, l2: -0.00135541066903853, l3: 0.0, l4: 0.0, l5: 0.0, l6: -0.00272477527321510, x1: 0.369213053974749, x2: 0.329043046533957, x3: 0.301743899491294, x4: 0.0}
{l1: 0.684000492058411, l2: -0.00188712842748965, l3: 0.0, l4: -0.00196211900247153, l5: 0.0, l6: -0.00345158308410752, x1: 0.500000000000002, x2: 0.0, x3: 0.499999999999998, x4: 0.0}
{l1: 1.21256205779059, l2: 0.000540153943596385, l3: -0.00289804375781042, l4: 0.0, l5: 0.0, l6: 0.0, x1: 0.0, x2: 0.275723132086073, x3: 0.0588378032372977, x4: 0.665439064676629}
{l1: 1.56877090247872, l2: 0.000775995367650160, l3: -0.00403358039997317, l4: -0.00168290287587900, l5: 0.0, l6: 0.0, x1: 0.0, x2: 0.0, x3: 0.147761240712766, x4: 0.852238759287234}